name: news_app
description: A Flutter News App using NewsAPI.org
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.6
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.0
  intl: ^0.18.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true